### ISSUE TITLE
Corrections in globals.cpp 

### ISSUE THREAD

**Issue by phsmip** [springmeyer/mapnik-jni#4]
After trying to compile mapnik-jni on Ubuntu 12.04, I detected several errors in file globals.cpp.
- Wrong signature for <code>valueOf</code> method on class <code>java.lang.Long</code>, the correct mapping is: <code>(J)Ljava/lang/Long</code> instead of <code>(I)Ljava/lang/Long</code>
- Method <code>setBool</code> and <code>setLong</code> on class <code>mapnik.Parameters</code> doesn't exist.

Regards

**Comment by springmeyer** [comment]
thanks for noticing. should be improved in https://github.com/springmeyer/mapnik-jni/commit/10b090911c9c70818adde01e3bc46290e48a22e2. Let me know how that works for you.
