### ISSUE TITLE
Problem loading plugin library: /usr/local/lib/mapnik/input/python.input

### ISSUE THREAD

**Issue by phsmip** [springmeyer/mapnik-jni#5]
When I run the test suite, no error occurs but a warn message is logged for all tests:

```
[junit] "Mapnik LOG> 2013-01-23 09:37:18:" Problem loading plugin library: /usr/local/lib/mapnik/input/python.input (dlopen failed - plugin likely has an unsatisfied dependency or incompatible ABI)
```

Is it a compilation problem with mapnik-jni or mapnik?
Could you help?

Thank you.

**Comment by springmeyer** [comment]
This is likely a problem in mapnik and that plugin, not the jni bindings. It is an experimental plugin so you can ignore this warning. If you want to get rid of it simply delete the plugin.
